# === CONSTANTS ===

# === INITIAL CONDITIONS AND GEOMETRY ===

TOTAL_LENGTH = 0.15 # m
RADIUS_CORE = 0.019 # m
TEMPERATURE_INITIAL = 287.0 # K
PRESSURE_INITIAL = 15.0E6 # Pa
PRESSURE_BOUNDARY = 2.0E6 # Pa 
TEMPERATURE_BOUNDARY = 287.0 # K

# === THERMOPHYSICAL PROPERTIES ===

DENSITY_HYDRATE = 0.91E3 # kg/m3
DENSITY_ROCK = 2.68E3 # kg/m3
DENSITY_WATER = 1E3 # kg/m3
HEAT_CAPACITY_GAS_P = 2E3 # J/(kg*K)
HEAT_CAPACITY_HYDRATE = 2220.0 # J/(kg*K)
HEAT_CAPACITY_ROCK = 835.0 # J/(kg*K)
HEAT_CAPACITY_WATER = 4.2E3 # J/(kg*K)
HEAT_CONDUCTIVITY_GAS = 0.034 # W/(m*K)
HEAT_CONDUCTIVITY_HYDRATE = 2.11 # W/(m*K)
HEAT_CONDUCTIVITY_ROCK = 2.0 # W/(m*K)
HEAT_CONDUCTIVITY_WATER = 0.58 # W/(m*K)
HEAT_CONDUCTIVITY_HYDRATE_ZONE = 5.57
HEAT_CONDUCTIVITY_DISS_ZONE = 2.73
GAS_CONSTANT_R = 520.0 # J/(kg*K)
CONVECTION_COEFFICIENT = 0.0 # 5.2; % W/(m2*K)
THROTTLING_COEFFICIENT = -1.5E-4 # J/(kg*Pa)

# === PETROPHYSICAL PROPERTIES ===

POROSITY = 0.188
PERMEABILITY = 97.98E-15 # m2
# VISCOSITYGAS = 1.8E-5 # Pa*s
VISCOSITY_WATER = 1.0E-3 # Pa*s
SATURATION_HYDRATE_INITIAL = 0.69
SATURATION_WATER_INITIAL = 0.30
SATURATION_WATER_BOUNDARY = 0.5
SATURATION_WATER_RESIDUAL = 0.2
SATURATION_GAS_RESIDUAL = 0.0
SPECIFIC_SURFACE_AREA = 2E6 # m2/m3, BEREA SANDSTONE - 0.93 m2/g
PRESSURE_CAPILLARY_E = 4.0E3 # Pa

# === HYDRATE PARAMETERS ===

MOLAR_WEIGHT_WATER = 18.01528E-3 # kg/mole 
MOLAR_WEIGHT_GAS = 16.04E-3 # kg/mole methane
HYDRATE_NUMBER = 5.96
A_W = 49.3185
B_W = -9459
DISSOCIATION_CONSTANT = 16.04 * 4.4E-16 # kg/(m2*Pa*s)
DELTA_E_BY_R = 9752.73 # K

# === DERIVATIVE PARAMETERS ===

DENSITY_GAS_INITIAL = PRESSURE_INITIAL / (GAS_CONSTANT_R * TEMPERATURE_INITIAL) # 27.87; % kg/m3
DENSITY_GAS_BOUNDARY = PRESSURE_BOUNDARY / (GAS_CONSTANT_R * TEMPERATURE_INITIAL) #  20.903;